version: '3.8'
name: lobe-chat-database
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=lobe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tttt20142024@  # Updated your Postgres password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Tttt20142024@
      - MINIO_DOMAIN=s3-api.taam.cloud  # Updated to your MinIO domain
      - MINIO_API_CORS_ALLOW_ORIGIN=https://chat.taam.cloud  # Updated to your LobeChat domain
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"

  logto:
    image: svhd/logto
    container_name: lobe-logto
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgresql://postgres:Tttt20142024@@postgresql:5432/logto  # Updated your Postgres DB URL
      - ENDPOINT=https://logto-auth.taam.cloud  # Updated your Logto API domain
      - ADMIN_ENDPOINT=https://logto-ui.taam.cloud  # Updated your Logto UI domain
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    ports:
      - '3210:3210'
    depends_on:
      - postgresql
      - minio
      - logto
<<<<<<< HEAD
=======
    env_file:
      - .env
>>>>>>> 31a717683f946b7975c2a2a77da8cb9b3db3074e
    # environment:
    #   - APP_URL=https://chat.taam.cloud/
    #   - KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ=
    #   - DATABASE_URL=postgresql://postgres:Tttt20142024@@postgresql:5432/lobe
    #   - NEXT_AUTH_SECRET=15hMVluPE5Y0HWSaGEi12+zY2zgpda2tifpB8c6c+oo=
    #   - NEXT_AUTH_SSO_PROVIDERS=logto
    #   - NEXTAUTH_URL=https://chat.taam.cloud/api/auth
    #   - AUTH_LOGTO_CLIENT_ID=5wetwreje63vxo2tp1iru
    #   - AUTH_LOGTO_CLIENT_SECRET=brUbMUgYME08Tz0ZWd1Gbg6kG5zqN2YY
    #   - AUTH_LOGTO_ISSUER=https://4523q9.logto.app/oidc
    #   - S3_ACCESS_KEY_ID=EW0tBjlYAFRWe0jNKHKs
    #   - S3_SECRET_ACCESS_KEY=CtgBiZKdL5uL5DL8ucRfdvqiRPOFe4udelmS4pLc
    #   - S3_ENDPOINT=https://s3-api.taam.cloud
    #   - S3_BUCKET=lobe
    #   - S3_PUBLIC_DOMAIN=https://s3-api.taam.cloud
    #   - S3_ENABLE_PATH_STYLE=1
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local
